name: PianoConcertoAccompaniment

channels:
  - conda-forge

dependencies:
  - python >=3.11,<3.12
  - pip

  # notebooks
  - jupyter
  - jupyterlab >=4.0,<5

  # core deps
  - pandas >=2.0,<3
  - tqdm
  - importnb >=2023.1

  # audio
  - librosa >=0.10,<0.11
  - ffmpeg

  # viz
  - k3d ==2.15.3

  - pip:
      - import-ipynb==0.1.4
      - hmc_mir==0.1.15
      - cython==3.0