name: PianoConcertoAccompaniment

channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python >=3.9,<3.10
  - jupyter
  - jupyterlab=4.0.12
  - pandas=1.5
  - importnb=2023.1
  - librosa=0.10
  - k3d=2.15.3
  - tqdm
  - pip:
    - import-ipynb==0.1.4
    - hmc_mir==0.1.15
    - cython==3.0