name: PianoConcertoAccompaniment

channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python >=3.9,<3.10
  - jupyter
  - pandas=1.5
  - importnb=2023.1
  - librosa=0.10
  - cython=0.29.32
  - tqdm
  - pip:
    - import-ipynb=0.1.4
    - hmc_mir